Repository TeamGoodGood/RelayNovel-iOS, pull requests merged in 2022-11, with the labels that each got.

#19 [2022/11/01] feat/releyProfileViewControllerHifiLayout >> Hi-fi 기반 RelayProfileViewController 레이아웃 설정
  Relay/Relay/ProfileView/RelayProfileViewController.swift
  Relay/Relay/ProfileView/Views/RelayNonLoginView.swift
  Relay/Relay/ProfileView/Views/RelayProfileUserActivityView.swift
  Relay/Relay/ProfileView/Views/RelayProfileUserInfoView.swift
  Relay/Relay/ProfileView/Views/RelayUserActivityCollectionViewCell.swift
Labels: ✨ Feat, 🎨Design

#23 [2022/11/2] feat/relayListViewLayout >> RelayListView 레이아웃 구현
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/Extension+/Extension+CALayer.swift
  Relay/Relay/Extension+/Extension+UILabel.swift
  Relay/Relay/Reusable/BasePaddingLabel.swift
  Relay/Relay/Reusable/RelayListView/RelayListCollectionViewCell.swift
  Relay/Relay/Reusable/RelayListView/RelayListHeaderView.swift
  Relay/Relay/Reusable/RelayListView/RelayListView.swift
Labels: ✨ Feat

#21 [2022/11/02] feat/RelayAgreementView >> 약관동의 뷰 구현
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/AgreementView/DetailViewController.swift
  Relay/Relay/AgreementView/RelayAgreementViewController.swift
  Relay/Relay/Extension+UIButton.swift
  Relay/Relay/Extension+UIImage.swift
  Relay/Relay/Login/RelayLoginViewController.swift
Labels: ✨ Feat, 🎨Design

#26 [2022/11/02] feat/colorFontExtension >> 색상, 폰트 extension 구현
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/Extension+/Extension+UIColor.swift
  Relay/Relay/Extension+/Extension+UILabel.swift
Labels: ✨ Feat

#28 [2022/11/02] design/relayProfileViewControllerStyleGuide >> RelayProfileViewController 색상/폰트/레이아웃을 스타일가이드에 맞게 수정
  Relay/Relay/ProfileView/RelayProfileViewController.swift
  Relay/Relay/ProfileView/Views/RelayNonLoginView.swift
  Relay/Relay/ProfileView/Views/RelayProfileUserActivityView.swift
  Relay/Relay/ProfileView/Views/RelayProfileUserInfoView.swift
  Relay/Relay/ProfileView/Views/RelayUserActivityCollectionViewCell.swift
Labels: 🎨Design

#24 [2022/11/02] feat/tabBarController >> TabBarController 구현
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/TabBarController.swift
Labels: ✨ Feat

#29 [2022/11/03] design/relayListViewStyleGuide >> RelayListView의 색상/폰트를 스타일가이드에 맞게 수정
  Relay/Relay/Reusable/RelayListView/RelayListCollectionViewCell.swift
  Relay/Relay/Reusable/RelayListView/RelayListHeaderView.swift
Labels: 🎨Design

#33 [2022/11/03] feat/relayAllReadyViewController >> RelayAllReadyView UI구현
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/AgreementView/RelayAgreementViewController.swift
  Relay/Relay/AllReadyView/RelayAllReadyViewController.swift
Labels: ✨ Feat

#31 [2022/11/03] -> feat/RelayPenNameViewController 구현
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/PenNameView/RelayPenNameViewController.swift
Labels: ✨ Feat

#36 [2022/11/03] feat/relayOnboardingViewController >> Onboarding UI 구현
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/Assets.xcassets/onboardingImage.imageset/Contents.json
  Relay/Relay/Assets.xcassets/onboardingImage.imageset/Image.png
  Relay/Relay/Onboarding/RelayFirstViewController.swift
  Relay/Relay/Onboarding/RelayOnboardingViewController.swift
  Relay/Relay/Onboarding/RelaySecondViewController.swift
  Relay/Relay/Onboarding/RelayThirdViewController.swift
Labels: ✨ Feat

#38 [2022/11/04] feat/relayMainViewController >> 메인 뷰 UI, 애니메이션 구현
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Relay/Relay/Assets.xcassets/1.imageset/Contents.json
  Relay/Relay/Assets.xcassets/1.imageset/Group 109.png
  Relay/Relay/Assets.xcassets/2.imageset/Contents.json
  Relay/Relay/Assets.xcassets/2.imageset/Group 107.png
  Relay/Relay/Assets.xcassets/3.imageset/Contents.json
  Relay/Relay/Assets.xcassets/3.imageset/Group 108.png
  Relay/Relay/Assets.xcassets/4.imageset/Contents.json
  Relay/Relay/Assets.xcassets/4.imageset/KakaoTalk_Photo_2022-11-03-23-07-21 1.png
  Relay/Relay/Assets.xcassets/5.imageset/Contents.json
  Relay/Relay/Assets.xcassets/5.imageset/KakaoTalk_Photo_2022-11-03-23-07-22 2.png
  Relay/Relay/Assets.xcassets/6.imageset/Contents.json
  Relay/Relay/Assets.xcassets/6.imageset/KakaoTalk_Photo_2022-11-03-23-07-22 3.png
  Relay/Relay/Assets.xcassets/7.imageset/Contents.json
  Relay/Relay/Assets.xcassets/7.imageset/KakaoTalk_Photo_2022-11-04-01-11-37.png
  Relay/Relay/MainView/RelayMainHostingController.swift
  Relay/Relay/MainView/Views/PageAnimationView.swift
  Relay/Relay/SceneDelegate.swift
Labels: ✨ Feat

#40 [2022/11/07] feat/relayBrowsingViewController >> 둘러보기 View UI 레이아웃 및 동작 구현
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/Assets.xcassets/RelayLogo.imageset/Contents.json
  Relay/Relay/Assets.xcassets/RelayLogo.imageset/RelayLogo.png
  Relay/Relay/BrowsingView/RelayBrowsingViewController.swift
  Relay/Relay/BrowsingView/Views/BrowsingTitleView.swift
  Relay/Relay/BrowsingView/Views/RelayBrowsingHeaderView.swift
  Relay/Relay/CategoryModalPresentationController.swift
  Relay/Relay/Reusable/CategoryView/RelayCategoryCollectionViewCell.swift
  Relay/Relay/Reusable/CategoryView/RelayCategoryViewController.swift
  Relay/Relay/Reusable/RelayListView/RelayListHeaderView.swift
  Relay/Relay/Reusable/RelayListView/RelayListView.swift
Labels: ✨ Feat

#43 [2022/11/09] feat/relay setting view controller >> 메인설정뷰, 내 정보뷰, 앱 설명 뷰 UI 구현
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/Assets.xcassets/RelayLilla.imageset/Contents.json
  Relay/Relay/Assets.xcassets/RelayLilla.imageset/Image.png
  Relay/Relay/SettingView/RelayAboutRelayViewController.swift
  Relay/Relay/SettingView/RelayMyInfoViewController.swift
  Relay/Relay/SettingView/RelaySettingViewController.swift
  Relay/Relay/SettingView/Views/RelayAboutRelayDescriptionView.swift
  Relay/Relay/SettingView/Views/RelaySettingTableViewCell.swift
Labels: ✨ Feat

#45 [2022/11/09] >> feat/relayWritingViewController >> 글쓰기 뷰 구현
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/AppDelegate.swift
  Relay/Relay/Extension+/Extension+UIViewController.swift
  Relay/Relay/PenNameView/RelayPenNameViewController.swift
  Relay/Relay/SceneDelegate.swift
  Relay/Relay/WritingView/RelayWritingViewController.swift
  Relay/Relay/WritingView/Views/DividerView.swift
  Relay/Relay/WritingView/Views/EventCollectionViewCell.swift
  Relay/Relay/WritingView/Views/TouchCollectionViewCell.swift
  Relay/Relay/WritingView/Views/WritingTitleView.swift
Labels: ✨ Feat

#47 [2022/11/09] >> feat/RelayNoticeViewController UI 구현
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/ NoticeView/RelayNoticeViewController.swift
  Relay/Relay/ NoticeView/Views/TableCellCustomCell.swift
Labels: ✨ Feat

#49 [2022/11/09] feat/relay delete account view controller >> 회원탈퇴 뷰 활성/비활성 UI 구현
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/RelayDeleteAccountAgreementView.swift
  Relay/Relay/RelayDeleteAccountUserActivityView.swift
  Relay/Relay/RelayDeleteAccountViewController.swift
Labels: ✨ Feat

#51 [2022/11/10] feat/relay terms and policies view >> 이용약관, 개인정보처리방침 스크롤뷰 UI 구현
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/SettingView/RelayPrivacyPolicyViewController.swift
  Relay/Relay/SettingView/RelayTermsAndConditionsViewController.swift
Labels: ✨ Feat

#61 [2022.11.11] feat/relay setting view connecting >> 설정 뷰 연결
  Relay/Relay/Scenes/DeleteAccountView/RelayDeleteAccountViewController.swift
  Relay/Relay/Scenes/SettingView/RelayMyInfoViewController.swift
  Relay/Relay/Scenes/SettingView/RelayPrivacyPolicyViewController.swift
  Relay/Relay/Scenes/SettingView/RelaySettingViewController.swift
  Relay/Relay/Scenes/SettingView/RelayTermsAndConditionsViewController.swift
Labels: ✨ Feat

#63 [2022.11.11] feat/RelayMainViewController >> 메인뷰 카드 데이터 받을 수 있도록 안에 UI들 따로 설정
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/Scenes/MainView/RelayMainViewController.swift
  Relay/Relay/Scenes/MainView/Views/CardView.swift
  Relay/Relay/Scenes/MainView/Views/PageAnimationView.swift
  Relay/Relay/Scenes/TabBarController.swift
Labels: ✨ Feat

#66 [2022/11/14] feat/relayBrowsingViewControllerConnection >> RelayBrowsingViewController -> RelayReadingViewController, RelayNoticeViewController 연결
  Relay/Relay/SceneDelegate.swift
  Relay/Relay/Scenes/BrowsingView/RelayBrowsingViewController.swift
  Relay/Relay/Scenes/ReadingView/RelayReadingViewController.swift
  Relay/Relay/Scenes/Reusable/RelayListView/RelayListView.swift
Labels: ✨ Feat

#70 [2022/11/15] feat/mainViewConnectWritingView >> 메인 뷰 글쓰기 뷰 연결
  Relay/Relay/Scenes/MainView/RelayMainViewController.swift
  Relay/Relay/Scenes/WritingView/RelayWritingViewController.swift
Labels: ✨ Feat

#72 [2022/11/16] refactor/relayCategoryViewController >> RelayCategoryViewController에 원하는 카테고리를 넣어 사용할 수 있도록 리팩토링, RelayWritingViewController와 연결
  Relay/Pods/Pods.xcodeproj/xcshareddata/xcschemes/RxCocoa.xcscheme
  Relay/Relay.xcodeproj/xcshareddata/xcschemes/Relay.xcscheme
  Relay/Relay/Relay.entitlements
  Relay/Relay/Scenes/BrowsingView/RelayBrowsingViewController.swift
  Relay/Relay/Scenes/Reusable/CategoryView/RelayCategoryViewController.swift
  Relay/Relay/Scenes/WritingView/RelayWritingViewController.swift
Labels: 🔨Refactor

#77 [Feat] Update API
  Relay/Relay/Model/User.swift
  Relay/Relay/Network/LoginAPI.swift
  Relay/Relay/Network/UserAPI.swift
Labels: ✨ Feat

#78 [2022/11/21] feat/relayProfileViewControllerConnection >> RelaySettingViewController, RelayNoticeViewController, RelayActivityViewController 연결
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/Scenes/ActivityView/RelayActivityViewController.swift
  Relay/Relay/Scenes/ProfileView/RelayProfileViewController.swift
  Relay/Relay/Scenes/ProfileView/Views/RelayProfileUserActivityView.swift
  Relay/Relay/Scenes/Reusable/RelayListView/RelayListView.swift
Labels: ✨ Feat

#79 [2022/11/21] design/detailDesignFix >> 디테일한 부분 디자인 수정
  Relay/Relay/Scenes/BrowsingView/RelayBrowsingViewController.swift
  Relay/Relay/Scenes/Extension+/Extension+UIImage.swift
  Relay/Relay/Scenes/MainView/RelayMainViewController.swift
  Relay/Relay/Scenes/NoticeView/RelayNoticeViewController.swift
  Relay/Relay/Scenes/TabBarController.swift
  Relay/Relay/Scenes/WritingView/RelayWritingViewController.swift
  Relay/Relay/Scenes/WritingView/Views/EventCollectionViewCell.swift
  Relay/Relay/Scenes/WritingView/Views/TouchCollectionViewCell.swift
Labels: ✨ Feat, 🎨Design

#81 [2022/10/25] Feat/relay launch screen >> LaunchScreen 추가
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/Assets.xcassets/launchScreen.imageset/Contents.json
  Relay/Relay/Assets.xcassets/launchScreen.imageset/Image.png
  Relay/Relay/Base.lproj/LaunchScreen.storyboard
  Relay/Relay/Scenes/Extension+/Extension+UIColor.swift
Labels: ✨ Feat

#86 [2022/11/23] refactor/onboarding view refactoring >> 온보딩뷰 리팩토링 및 페이지컬 오류 해결
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/Scenes/OnboardingView/RelayFirstViewController.swift
  Relay/Relay/Scenes/OnboardingView/RelayOnboardingDataModel.swift
  Relay/Relay/Scenes/OnboardingView/RelayOnboardingViewCell.swift
  Relay/Relay/Scenes/OnboardingView/RelayOnboardingViewController.swift
  Relay/Relay/Scenes/OnboardingView/RelaySecondViewController.swift
  Relay/Relay/Scenes/OnboardingView/RelayThirdViewController.swift
Labels: 🔨Refactor

#83 [2022/11/22] Feat/navigationLogoButtonDetail >> 네비게이션 로고버튼 비활성화 및 색 변경 방지
  Relay/Relay/Scenes/BrowsingView/RelayBrowsingViewController.swift
  Relay/Relay/Scenes/MainView/RelayMainViewController.swift
Labels: ✨ Feat

#88 [2022/11/23] feat/allFunctionCheck >> 전체기능 확인 및 데이터전달로직 구현
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/Assets.xcassets/1.imageset/1.png
  Relay/Relay/Assets.xcassets/1.imageset/Contents.json
  Relay/Relay/Assets.xcassets/1.imageset/Group 109.png
  Relay/Relay/Assets.xcassets/2.imageset/2.png
  Relay/Relay/Assets.xcassets/2.imageset/Contents.json
  Relay/Relay/Assets.xcassets/2.imageset/Group 107.png
  Relay/Relay/Assets.xcassets/3.imageset/3.png
  Relay/Relay/Assets.xcassets/3.imageset/Contents.json
  Relay/Relay/Assets.xcassets/3.imageset/Group 108.png
  Relay/Relay/Model/BGM.swift
  Relay/Relay/Model/Category.swift
  Relay/Relay/Model/Genre.swift
  Relay/Relay/Model/MockData/MockRecommend.swift
  Relay/Relay/Model/MockData/MockRelay.swift
  Relay/Relay/Model/MockData/MockStory.swift
  Relay/Relay/Model/MockData/MockUser.swift
  Relay/Relay/Model/Story.swift
  Relay/Relay/Scenes/ActivityView/RelayActivityViewController.swift
  Relay/Relay/Scenes/BrowsingView/RelayBrowsingViewController.swift
  Relay/Relay/Scenes/Extension+/Extension+Double.swift
  Relay/Relay/Scenes/MainView/RelayMainViewController.swift
  Relay/Relay/Scenes/MainView/Views/CardView.swift
  Relay/Relay/Scenes/MainView/Views/PageAnimationView.swift
  Relay/Relay/Scenes/ReadingView/RelayReadingViewController.swift
  Relay/Relay/Scenes/ReadingView/Views/BodyCollectionViewCell.swift
  Relay/Relay/Scenes/ReadingView/Views/ReadingBodyView.swift
  Relay/Relay/Scenes/ReadingView/Views/ReadingNoticeView.swift
  Relay/Relay/Scenes/ReadingView/Views/RelayReadingCoverView.swift
  Relay/Relay/Scenes/ReadingView/Views/RelayReadingFinishFooterView.swift
  Relay/Relay/Scenes/ReadingView/Views/RelayReadingFooterView.swift
  Relay/Relay/Scenes/ReadingView/Views/RelayReadingWriteView.swift
  Relay/Relay/Scenes/Reusable/CategoryView/RelayCategoryCollectionViewCell.swift
  Relay/Relay/Scenes/Reusable/CategoryView/RelayCategoryViewController.swift
  Relay/Relay/Scenes/Reusable/RelayListView/RelayListCollectionViewCell.swift
  Relay/Relay/Scenes/WritingView/RelayWritingViewController.swift
Labels: ✨ Feat

#89 [2022/11/23] feat/onboarding logic >> 온보딩 최초 실행 및 로그인 여부 확인 로직 구현
  Relay/Relay/Scenes/TabBarController.swift
Labels: ✨ Feat

#90 [2022/11/23] design/settingNavigationBarCustom >> 세팅뷰 및 하위 뷰들의 네비게이션바 커스텀
  Relay/Relay/Scenes/DeleteAccountView/RelayDeleteAccountViewController.swift
  Relay/Relay/Scenes/SettingView/RelayAboutRelayViewController.swift
  Relay/Relay/Scenes/SettingView/RelayMyInfoViewController.swift
  Relay/Relay/Scenes/SettingView/RelaySettingViewController.swift
Labels: 🎨Design

#93 [2022/11/24] design/relayWritingViewControllerButtons >> 완주버튼, 좋아요버튼 디자인 수정
  Relay/Relay/Scenes/ReadingView/Views/RelayReadingCoverView.swift
  Relay/Relay/Scenes/ReadingView/Views/RelayReadingFinishFooterView.swift
  Relay/Relay/Scenes/ReadingView/Views/RelayReadingFooterView.swift
Labels: 🎨Design

#95 [2022/11/26] feat/relayWritingViewControllerPushStyle >> RelayReadingViewController가 나타날 때 탭바가 안보이도록 구현
  Relay/Relay/Scenes/ActivityView/RelayActivityViewController.swift
  Relay/Relay/Scenes/BrowsingView/RelayBrowsingViewController.swift
  Relay/Relay/Scenes/MainView/RelayMainViewController.swift
  Relay/Relay/Scenes/TabBarController.swift
Labels: ✨ Feat, 🎨Design
