Repository TeamGoodGood/RelayNovel-iOS, pull requests merged in 2022-12, with the labels that each got.

#100 [2022/12/02] Feat/alarmlogic >> 알람 뷰 로직 구현, 디자인 수정 반영
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/Model/MockData/MockNotice.swift
  Relay/Relay/Scenes/NoticeView/RelayNoticeViewController.swift
  Relay/Relay/Scenes/NoticeView/Views/TableCellCustomCell.swift
Labels: ✨ Feat, 🎨Design

#103 [2022/12/05] Feat/dateFormatter >> 날짜 로직 구현
  Relay/Relay/Scenes/Extension+/Extension+Double.swift
  Relay/Relay/Scenes/Extension+/Extension+UIViewController.swift
  Relay/Relay/Scenes/NoticeView/Views/TableCellCustomCell.swift
Labels: ✨ Feat

#105 [Feat] #104 ProfileView, ListView에 dateDifferenceToString 함수 적용
  Relay/Relay/Scenes/ActivityView/RelayActivityViewController.swift
  Relay/Relay/Scenes/BrowsingView/RelayBrowsingViewController.swift
Labels: ✨ Feat

#110 [2022/12/07] feat/RelayReadingViewControllerWriterFiltering >> RelayReadingViewController의 완주게시글의 참여작가가 동일인물이 있을 시 걸러주는 기능 구현
  Relay/Relay/Scenes/ReadingView/Views/RelayReadingFinishFooterView.swift
Labels: ✨ Feat

#111 [2022/12/07] feat/fixNovel >> 소설 내용 변경
  Relay/Relay/Model/MockData/MockRecommend.swift
  Relay/Relay/Model/MockData/MockRelay.swift
  Relay/Relay/Model/MockData/MockStory.swift
Labels: ✨ Feat

#118 [2022/12/08] fix/mainViewControllerAudio >> RelayMainViewController에서의 플레이리스트 재생오류 수정
  Relay/Relay/Scenes/MainView/RelayMainViewController.swift
  Relay/Relay/Scenes/MainView/Views/CardView.swift
Labels: 🐞Fix

#113 [2022/12/08] Feat/showcase >> MainView 소설 내용 변경
  Relay/Relay/Model/MockData/MockRelay.swift
  Relay/Relay/Model/MockData/MockStory.swift
Labels: ✨ Feat

#123 [2022/12/09] fix/mainViewFix >> 캐릭터 3개 변경, MainView 캐릭터 크기, 위치, 뒷 배경 높이 수정
  Relay/Relay/Assets.xcassets/4.imageset/Contents.json
  Relay/Relay/Assets.xcassets/4.imageset/Group 105.png
  Relay/Relay/Assets.xcassets/4.imageset/KakaoTalk_Photo_2022-11-03-23-07-21 1.png
  Relay/Relay/Assets.xcassets/5.imageset/Contents.json
  Relay/Relay/Assets.xcassets/5.imageset/Group 206.png
  Relay/Relay/Assets.xcassets/5.imageset/KakaoTalk_Photo_2022-11-03-23-07-22 2.png
  Relay/Relay/Assets.xcassets/6.imageset/Contents.json
  Relay/Relay/Assets.xcassets/6.imageset/Group 207.png
  Relay/Relay/Assets.xcassets/6.imageset/KakaoTalk_Photo_2022-11-03-23-07-22 3.png
  Relay/Relay/Scenes/MainView/Views/PageAnimationView.swift
Labels: 🎨Design

#127 [2022/12/10] Feat/fixCardView >> 플레이리스트 제목을 해시태그로 수정
  Relay/Relay/Model/BGM.swift
  Relay/Relay/Scenes/MainView/Views/CardView.swift
Labels: ✨ Feat

#129 [2022/12/10] feat/RelayReadingView >> 바통터치를 눌렀을 경우 keyboard를 자동으로 띄우고, 그 크기만큼 자동으로 스크롤 구현
  Relay/Relay/Info.plist
  Relay/Relay/Scenes/ReadingView/RelayReadingViewController.swift
Labels: ✨ Feat

#126 [2022/12/10] design/relayCategoryViewControllerCellUnderline >> RelayCategoryViewController이 플레이리스트를 받을때 첫번째 셀에 밑줄이 안나타나도록 구현 및 높이수정
  Relay/Relay/Scenes/BrowsingView/RelayBrowsingViewController.swift
  Relay/Relay/Scenes/Reusable/CategoryModal/CategoryModalPresentationController.swift
  Relay/Relay/Scenes/Reusable/CategoryView/RelayCategoryViewController.swift
  Relay/Relay/Scenes/WritingView/RelayWritingViewController.swift
Labels: ✨ Feat, 🎨Design

#131 [22/12/11] Feat/relayReadingVCHeartButton >> 읽기뷰 '좋아요'버튼 기능 구현
  Relay/Relay/Scenes/ReadingView/RelayReadingViewController.swift
Labels: ✨ Feat

#133 [2022/12/12] fix/relayBrowsingVieweStatusLabel >> 새로운 릴레이 작성 후 RelayBrowsingViewController에서 각 셀들의 '달리는중', '완주'의 색상이 뒤바뀌게 나타나는 오류 수정
  Relay/Relay/Scenes/Reusable/RelayListView/RelayListCollectionViewCell.swift
Labels: 🐞Fix

#138 [2022/12/12] Feat/mypageUIDesignChange >> 마이페이지 디자인 UI 변경
  Relay/Relay/Scenes/ProfileView/Views/RelayProfileUserInfoView.swift
  Relay/Relay/Scenes/ProfileView/Views/RelayUserActivityCollectionViewCell.swift
Labels: 🎨Design

#139 [2022/12/12] feat/mockStoryFilterAndDataConnection >> MockStory에 달리는중/완주, 최신순/오래된순/추천순, 카테고리별, 내가 시작한/참여한/좋아요한 Story 제공 필터기능 구현 및 해당 View 연결 구현
  Relay/Relay/Model/MockData/MockRelay.swift
  Relay/Relay/Model/MockData/MockStory.swift
  Relay/Relay/Scenes/ActivityView/RelayActivityViewController.swift
  Relay/Relay/Scenes/BrowsingView/RelayBrowsingViewController.swift
  Relay/Relay/Scenes/ReadingView/Views/ReadingBodyView.swift
  Relay/Relay/Scenes/Reusable/RelayListView/RelayListHeaderView.swift
Labels: ✨ Feat

#130 [2022/12/11] Feat/writing view fix >> writingView 디자인 변경에 맞춰 UI 수정, 음소거 버튼 동작 구현
  Relay/Relay/Scenes/NoticeView/RelayNoticeViewController.swift
  Relay/Relay/Scenes/WritingView/RelayWritingViewController.swift
  Relay/Relay/Scenes/WritingView/Views/WritingTitleView.swift
Labels: ✨ Feat, 🎨Design
