Repository TeamGoodGood/RelayNovel-iOS, pull requests merged in 2022-10, with the labels that each got.

#3 [2022/10/25] build/gitignoreSetting >> Xcode, macOS, Swift 관련 gitignore 설정
  .gitignore
Labels: 🤖 Build

#7 [2022/10/27] fix/snapKit >> SnapKit이 import가 안되는 오류 해결
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Relay/Relay/ViewController.swift
Labels: 🐞Fix

#11 [2022/10/30] feat/loginview >> RelayLoginViewController 구현
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/Assets.xcassets/Lilla.imageset/Contents.json
  Relay/Relay/Assets.xcassets/Lilla.imageset/제목_없는_아트워크 1.png
  Relay/Relay/Login/RelayLoginViewController.swift
Labels: ✨ Feat

#13 [2022/10/31] feat/relayProfileViewControllerLayout >> Lo-fi 기반 RelayProfileViewController 레이아웃 설정
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/Extension+UILabel.swift
  Relay/Relay/ProfileView/RelayProfileViewController.swift
  Relay/Relay/ProfileView/Views/RelayNonLoginView.swift
  Relay/Relay/ProfileView/Views/RelayProfileUserActivityView.swift
  Relay/Relay/ProfileView/Views/RelayProfileUserInfoView.swift
  Relay/Relay/ProfileView/Views/RelayUserActivityCollectionViewCell.swift
Labels: ✨ Feat
