Repository TeamGoodGood/RelayNovel-iOS, pull requests merged in 2023-03, with the labels that each got.

#149 [2022/02/22] fix/relayMainView/pageAnimation >> RelayMainViewController의 CardView 재생버튼이 애니매이션되면 초기화되는 버그 수정
  Relay/Relay/Scenes/MainView/RelayMainViewController.swift
  Relay/Relay/Scenes/MainView/Views/CardView.swift
  Relay/Relay/Scenes/TabBarController.swift
Labels: 🐞Fix

#155 [2023/03/05] Feat/connectUserAccountVariable >> 설정>내정보>계정에서 내 계정을 불러오는 변수연결
  Relay/Relay/Scenes/SettingView/RelayMyInfoViewController.swift
Labels: 🔨Refactor

#151 [2023/03/02] Feat/connectZeroContentsView >> 컨텐츠가 없을 때의 화면 디자인 및 로직 구현
  Relay/Relay.xcodeproj/project.pbxproj
  Relay/Relay/Scenes/ActivityView/RelayActivityViewController.swift
  Relay/Relay/Scenes/BrowsingView/RelayBrowsingViewController.swift
  Relay/Relay/Scenes/Extension+/Extension+UICollectionView.swift
  Relay/Relay/Scenes/Extension+/Extension+UITableView.swift
  Relay/Relay/Scenes/NoticeView/RelayNoticeViewController.swift
  Relay/Relay/Scenes/Reusable/RelayListView/RelayListEmptyView.swift
Labels: ✨ Feat
